#!/usr/bin/env bash
set -euo pipefail

GPU_IDS=${GPU_IDS:-0}
NUM_VIEWS=${NUM_VIEWS:-2}
MAX_STEPS=${MAX_STEPS:-1000}
MV_ARCH=${MV_ARCH:-adapter}
MV_ADAPTER_DIM=${MV_ADAPTER_DIM:-128}
MV_ATTN_MODE=${MV_ATTN_MODE:-full_view}
INJECT_SINGLE_BLOCKS=${INJECT_SINGLE_BLOCKS:-1}
SINGLE_BLOCK_STRIDE=${SINGLE_BLOCK_STRIDE:-4}

OUTPUT_DIR=${OUTPUT_DIR:-outputs/flux_mvs_steps${MAX_STEPS}_views${NUM_VIEWS}_${MV_ARCH}_dim${MV_ADAPTER_DIM}_${MV_ATTN_MODE}}
MV_CKPT=${MV_CKPT:-${OUTPUT_DIR}/mv_adapter_last.pt}
OUT=${OUT:-${OUTPUT_DIR}/sample_S${MAX_STEPS}_V${NUM_VIEWS}_${MV_ARCH}_D${MV_ADAPTER_DIM}_${MV_ATTN_MODE}.jpg}

GPU_IDS=$GPU_IDS \
MV_CKPT=$MV_CKPT \
MANIFEST=${MANIFEST:-data/samples/stride_10_angle_15_v2_val_samples.jsonl} \
SAMPLE_INDEX=${SAMPLE_INDEX:-0} \
NUM_VIEWS=$NUM_VIEWS \
MV_ARCH=$MV_ARCH \
MV_ADAPTER_DIM=$MV_ADAPTER_DIM \
MV_ATTN_MODE=$MV_ATTN_MODE \
INJECT_SINGLE_BLOCKS=$INJECT_SINGLE_BLOCKS \
SINGLE_BLOCK_STRIDE=$SINGLE_BLOCK_STRIDE \
OUT=$OUT \
bash scripts/30_infer_flux_mvs_manifest.sh
