#!/usr/bin/env bash
set -euo pipefail

GPU_IDS=${GPU_IDS:-3}
NUM_VIEWS=${NUM_VIEWS:-2}
MAX_STEPS=${MAX_STEPS:-5000}
MV_ARCH=${MV_ARCH:-adapter}
MV_ADAPTER_DIM=${MV_ADAPTER_DIM:-512}
MV_ATTN_MODE=${MV_ATTN_MODE:-full_view}
LR=${LR:-1e-4}
BATCH_SIZE=${BATCH_SIZE:-1}
GRAD_ACCUM=${GRAD_ACCUM:-8}
INJECT_SINGLE_BLOCKS=${INJECT_SINGLE_BLOCKS:-1}
SINGLE_BLOCK_STRIDE=${SINGLE_BLOCK_STRIDE:-4}
PSEUDO_GENERAL_PROB=${PSEUDO_GENERAL_PROB:-0.15}

OUTPUT_DIR=${OUTPUT_DIR:-outputs/flux_mvs_steps${MAX_STEPS}_views${NUM_VIEWS}_${MV_ARCH}_dim${MV_ADAPTER_DIM}_${MV_ATTN_MODE}}

GPU_IDS=$GPU_IDS \
TRAIN_MANIFEST=${TRAIN_MANIFEST:-data/samples/stride_10_angle_15_v2_train_samples.jsonl} \
NUM_VIEWS=$NUM_VIEWS \
RESOLUTION=${RESOLUTION:-512} \
BATCH_SIZE=$BATCH_SIZE \
GRAD_ACCUM=$GRAD_ACCUM \
MAX_STEPS=$MAX_STEPS \
LR=$LR \
MV_ARCH=$MV_ARCH \
MV_ADAPTER_DIM=$MV_ADAPTER_DIM \
MV_ATTN_MODE=$MV_ATTN_MODE \
INJECT_SINGLE_BLOCKS=$INJECT_SINGLE_BLOCKS \
SINGLE_BLOCK_STRIDE=$SINGLE_BLOCK_STRIDE \
PSEUDO_GENERAL_PROB=$PSEUDO_GENERAL_PROB \
OUTPUT_DIR=$OUTPUT_DIR \
bash scripts/20_train_flux_mvs_stage1.sh
