#!/usr/bin/env bash
set -euo pipefail

GPU_IDS=${GPU_IDS:-1}
TRAIN_MANIFEST=${TRAIN_MANIFEST:-data/train_samples_angle_60.jsonl}
OUTPUT_DIR=${OUTPUT_DIR:-outputs/flux_mvs_stage2_v1}
NUM_VIEWS=${NUM_VIEWS:-4}
RESOLUTION=${RESOLUTION:-512}
BATCH_SIZE=${BATCH_SIZE:-1}
GRAD_ACCUM=${GRAD_ACCUM:-8}
MAX_STEPS=${MAX_STEPS:-20000}
LR=${LR:-1e-4}
MV_ARCH=${MV_ARCH:-adapter}
MV_ADAPTER_DIM=${MV_ADAPTER_DIM:-512}
MV_ATTN_MODE=${MV_ATTN_MODE:-full_view}
INJECT_SINGLE_BLOCKS=${INJECT_SINGLE_BLOCKS:-0}
SINGLE_BLOCK_STRIDE=${SINGLE_BLOCK_STRIDE:-4}
PSEUDO_GENERAL_PROB=${PSEUDO_GENERAL_PROB:-0.15}
RESUME_MV_CKPT=${RESUME_MV_CKPT:-}

GPU_IDS=$GPU_IDS \
TRAIN_MANIFEST=$TRAIN_MANIFEST \
OUTPUT_DIR=$OUTPUT_DIR \
NUM_VIEWS=$NUM_VIEWS \
RESOLUTION=$RESOLUTION \
BATCH_SIZE=$BATCH_SIZE \
GRAD_ACCUM=$GRAD_ACCUM \
MAX_STEPS=$MAX_STEPS \
LR=$LR \
MV_ARCH=$MV_ARCH \
MV_ADAPTER_DIM=$MV_ADAPTER_DIM \
MV_ATTN_MODE=$MV_ATTN_MODE \
INJECT_SINGLE_BLOCKS=$INJECT_SINGLE_BLOCKS \
SINGLE_BLOCK_STRIDE=$SINGLE_BLOCK_STRIDE \
PSEUDO_GENERAL_PROB=$PSEUDO_GENERAL_PROB \
RESUME_MV_CKPT=$RESUME_MV_CKPT \
bash scripts/21_train_flux_mvs_stage2.sh
