GPU_IDS=2 \
TRAIN_MANIFEST=data/stride_10_angle_30_train_samples.jsonl \
OUTPUT_DIR=outputs/flux_mvs_stage1_num_view4 \
NUM_VIEWS=4 \
RESOLUTION=512 \
BATCH_SIZE=1 \
GRAD_ACCUM=8 \
MAX_STEPS=5000 \
LR=1e-4 \
MV_ADAPTER_DIM=512 \
bash scripts/20_train_flux_mvs_stage1.sh